// Multi-language word banks optimized for typing tests.
// Each language has ~300 common words (3-8 chars, no punctuation).

const english = [
  "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
  "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
  "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
  "an", "will", "my", "one", "all", "would", "there", "their", "what",
  "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
  "when", "make", "can", "like", "time", "no", "just", "him", "know",
  "take", "people", "into", "year", "your", "good", "some", "could",
  "them", "see", "other", "than", "then", "now", "look", "only", "come",
  "its", "over", "think", "also", "back", "after", "use", "two", "how",
  "our", "work", "first", "well", "way", "even", "new", "want", "because",
  "any", "these", "give", "day", "most", "been", "great", "between",
  "need", "large", "might", "right", "still", "old", "place", "same",
  "tell", "become", "show", "leave", "both", "own", "part", "begin",
  "turn", "hand", "high", "move", "long", "live", "keep", "last", "ask",
  "few", "try", "call", "name", "word", "read", "four", "run", "find",
  "set", "each", "let", "city", "tree", "cross", "farm", "hard", "start",
  "light", "story", "saw", "far", "sea", "draw", "left", "late", "run",
  "dont", "while", "press", "close", "night", "real", "life", "head",
  "hold", "hope", "door", "room", "open", "seem", "next", "play", "walk",
  "song", "half", "fire", "blue", "free", "north", "round", "deep",
  "stand", "past", "dark", "road", "green", "south", "black", "short",
  "table", "group", "music", "river", "carry", "watch", "paper", "white",
  "child", "power", "build", "feed", "reach", "serve", "shape", "visit",
  "field", "smile", "stone", "voice", "enter", "learn", "offer", "check",
  "cover", "touch", "break", "dress", "track", "glass", "plant", "class",
  "peace", "share", "clean", "black", "guide", "range", "dream", "scale",
  "match", "south", "trust", "stone", "store", "value", "ready", "speed",
  "wonder", "color", "bring", "thank", "catch", "force", "spend", "focus",
  "piano", "beach", "trade", "model", "major", "human", "image", "space",
  "clear", "price", "prove", "least", "stage", "topic", "avoid", "south",
  "plain", "movie", "raise", "throw", "noise", "shirt", "sugar", "write",
  "smell", "worry", "brain", "third", "month", "fifty", "count", "brain",
  "clock", "paint", "solve", "phone", "award", "metal", "sharp", "dance",
  "sweet", "sound", "hotel", "skill", "drive", "elite", "guard", "fresh",
  "limit", "enjoy", "sport", "drink", "court", "layer", "storm", "chest",
  "coach", "shoot", "ideal", "south", "grill", "pilot", "mouse", "sweep",
  "truck", "brush", "fruit", "claim", "angel", "breed", "ocean", "crash",
  "robot", "chase", "final", "brain", "fault", "tower", "lunch", "split",
  "ratio", "young", "opera", "delay", "craft", "blame", "tiger", "label",
  "ghost", "armed", "minus", "panel", "minor", "treat", "celeb", "magic",
  "topic", "fever", "royal", "rider", "solar", "laser", "vocal", "bonus",
  "bench", "slice", "coral", "voter", "candy", "arrow", "vinyl", "tribe",
  "sauce", "cabin", "forum", "blade", "asset", "medal", "spine", "mayor",
  "rival", "arena", "lodge", "stove", "cargo", "wagon", "clone", "optic",
  "torch", "haste", "flame", "widow", "radar", "irony", "pearl", "wrist",
  "reign", "hobby", "flute", "liner", "orbit", "arter", "chimp", "squad",
  "crane", "ditch", "cease", "dairy", "satin", "ethic", "curse", "bloom",
  "tempo", "vivid", "oxide", "bowel", "chant", "bride", "trait", "spicy",
  "humid", "brink", "scent", "glare", "pluck", "salon", "mango", "stalk",
  "vigor", "aisle", "haunt", "leafy", "satin", "yield", "quest", "frost",
  "sprig", "whirl", "lowly", "brawn", "grime", "plume", "stalk", "vapor",
  "cloak", "blush", "flair", "abyss", "thine", "gravy", "snare", "sooth",
];

const hindi = [
  "ek", "ki", "ke", "hai", "ka", "mein", "bhi", "tha", "se", "ko",
  "par", "yeh", "woh", "kya", "nahi", "tum", "hum", "aap", "tha", "the",
  "bahut", "sab", "kuch", "agar", "jab", "tab", "kaise", "kyon", "kab",
  "yahaan", "vahaan", "andar", "baahar", "achchha", "bura", "bada", "chhota",
  "naya", "purana", "sundar", "garam", "thanda", "pani", "khana", "ghar",
  "kam", "din", "raat", "subah", "shaam", "aaj", "kal", "parson", "abhi",
  "sirf", "itna", "utna", "jitna", "pata", "samay", "baat", "kaam",
  "log", "duniya", "desh", "shahar", "gaon", "rasta", "bagal", "sabun",
  "aankh", "kaan", "naak", "munh", "haath", "pair", "dil", "dimag",
  "sach", "jhooth", "pyar", "nafrat", "dost", "dushman", "jeevan", "maut",
  "ekta", "shakti", "kranti", "shanti", "pragati", "samman", "abhimaan",
  "sahitya", "sangeet", "nrtya", "chitrakala", "shiksha", "vidya", "gyan",
  "suraj", "chand", "tare", "aakash", "prithvi", "samudra", "parvat", "nadi",
  "hawa", "aag", "mitti", "ped", "phool", "phal", "beej", "patte",
  "sher", "haathi", "bandar", "mor", "koyal", "machhli", "pakshi", "saanp",
  "rang", "safed", "kala", "lal", "hara", "neela", "peela", "gulabi",
  "sankhya", "ek", "do", "teen", "char", "paanch", "chhah", "saat",
  "aath", "nau", "das", "gyarah", "barah", "terah", "chaudah", "pandrah",
  "solah", "satrah", "atharah", "unnis", "bees", "pachas", "sau", "hazar",
];

const indonesian = [
  "dan", "di", "ke", "dari", "yang", "ini", "itu", "dengan", "pada",
  "adalah", "untuk", "tidak", "saya", "akan", "kami", "mereka", "kamu",
  "dia", "ada", "bisa", "sudah", "atau", "juga", "telah", "sangat",
  "semua", "lebih", "banyak", "bagi", "karena", "tetapi", "sebagai",
  "antara", "seperti", "bahwa", "dalam", "oleh", "saat", "setelah",
  "sebelum", "selama", "setiap", "hanya", "masih", "baru", "lain",
  "rumah", "makan", "minum", "tidur", "jalan", "mobil", "sepeda",
  "sekolah", "buku", "tulis", "baca", "kerja", "uang", "beli", "jual",
  "besar", "kecil", "tinggi", "rendah", "cepat", "lambat", "kuat", "lemah",
  "panjang", "pendek", "lebar", "sempit", "berat", "ringan", "tua", "muda",
  "bagus", "jelek", "indah", "cantik", "tampan", "sehat", "sakit", "bahagia",
  "sedih", "marah", "takut", "berani", "senang", "bosan", "malas", "rajin",
  "pintar", "bodoh", "kaya", "miskin", "sibuk", "lengang", "ramai", "sepi",
  "darat", "laut", "udara", "api", "tanah", "angin", "hujan", "panas",
  "dingin", "kering", "basah", "gelap", "terang", "siang", "malam", "pagi",
  "sore", "hari", "bulan", "bintang", "matahari", "gunung", "sungai", "hutan",
  "kota", "desa", "pulau", "pantai", "jalan", "jembatan", "pasar", "toko",
  "kantor", "rumah sakit", "hotel", "restoran", "masjid", "gereja", "pura",
  "beras", "gula", "garam", "minyak", "susu", "telur", "daging", "ikan",
  "sayur", "buah", "kopi", "teh", "roti", "kue", "nasi", "mie",
  "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan",
  "sembilan", "sepuluh", "ratus", "ribu", "juta", "miliar", "nol", "koma",
  "bola", "musik", "film", "lagu", "tari", "lukis", "gambar", "foto",
  "baju", "celana", "sepatu", "topi", "tas", "jam", "cincin", "kaca",
  "meja", "kursi", "lemari", "tempat", "pintu", "jendela", "lantai", "atap",
  "ibu", "bapak", "anak", "kakak", "adik", "nenek", "kakek", "paman",
];

const tagalog = [
  "ang", "ng", "sa", "mga", "at", "ay", "ko", "mo", "si", "na",
  "ito", "may", "hindi", "ako", "ikaw", "sila", "kami", "tayo", "kayo",
  "iyon", "dito", "doon", "kung", "para", "dahil", "kaya", "pero", "o",
  "isa", "dalawa", "tatlo", "apat", "lima", "anim", "pito", "walo",
  "siyam", "sampu", "bahay", "tao", "bata", "lalaki", "babae", "nanay",
  "tatay", "anak", "kapatid", "kaibigan", "guro", "maganda", "mabait",
  "masaya", "malungkot", "galit", "gutom", "pagod", "tubig", "pagkain",
  "kanin", "isda", "karne", "gulay", "prutas", "gatas", "kape", "tsaa",
  "araw", "buwan", "bituin", "ulan", "hangin", "lupa", "dagat", "ilog",
  "bundok", "puno", "bulaklak", "ibon", "aso", "pusa", "isda", "ahas",
  "malaki", "maliit", "bago", "luma", "mataas", "mababa", "mahaba", "maikli",
  "mabilis", "mabagal", "mainit", "malamig", "puti", "itim", "pula", "asul",
  "berde", "dilaw", "buhay", "patay", "tama", "mali", "tunay", "peke",
  "mahal", "mura", "malinis", "marumi", "malakas", "mahina", "bata", "matanda",
  "aral", "laro", "tulog", "gising", "tawa", "iyak", "lakad", "takbo",
  "kain", "inom", "sabi", "tanong", "sagot", "bigay", "kuha", "bili",
  "bukas", "sarado", "pasok", "labas", "taas", "baba", "loob", "labas",
  "likod", "harap", "kanan", "kaliwa", "itaas", "ibaba", "malapit", "malayo",
  "isip", "puso", "mata", "tainga", "ilong", "bibig", "kamay", "paa",
  "linggo", "buwan", "taon", "oras", "minuto", "araw", "gabi", "umaga",
  "hapon", "tanghali", "ngayon", "mamaya", "kahapon", "bukas", "sandali",
  "lugar", "bayad", "tawag", "sulat", "kuwento", "awit", "sayaw", "guhit",
  "langit", "lupa", "ilaw", "anino", "tulay", "daan", "bato", "kahoy",
];

const spanish: string[] = [
  "que", "los", "las", "del", "por", "con", "una", "para", "como",
  "mas", "pero", "sus", "este", "entre", "hay", "fue", "era", "muy",
  "hace", "hacer", "cada", "otro", "otra", "tambien", "todo", "todos",
  "bien", "poco", "mucho", "hombre", "mujer", "vida", "mundo", "tiempo",
  "tierra", "luz", "agua", "fuego", "cielo", "mar", "aire", "gran",
  "verde", "blanco", "negro", "rojo", "azul", "mano", "ojos", "casa",
  "calle", "ciudad", "campo", "noche", "tarde", "manana", "bueno", "malo",
  "mayor", "menor", "lejos", "cerca", "fuerte", "debil", "joven", "viejo",
  "nuevo", "claro", "oscuro", "triste", "feliz", "pronto", "necesito",
  "nombre", "pueblo", "historia", "palabra", "persona", "familia", "amigo",
  "trabajo", "dinero", "cuerpo", "mente", "alma", "sangre", "carne", "hueso",
  "padre", "madre", "hijo", "hermano", "señor", "niño", "niña", "abuelo",
  "calor", "frio", "lluvia", "viento", "nieve", "flor", "arbol", "pajaro",
  "perro", "gato", "pez", "vaca", "lobo", "monte", "rio", "lago",
  "pan", "sal", "vino", "leche", "carne", "fruta", "queso", "huevo",
  "mesa", "silla", "puerta", "ventana", "cama", "techo", "piso", "llave",
  "nacer", "morir", "vivir", "sentir", "pensar", "creer", "saber", "decir",
  "hablar", "venir", "llegar", "dejar", "poner", "tener", "poder", "gustar",
  "mirar", "pedir", "perder", "salir", "entrar", "comer", "reir", "besar",
  "llorar", "abrir", "cerrar", "subir", "bajar", "buscar", "tomar", "besar",
];

export const LANGUAGES: Record<string, { name: string; nativeName: string; words: string[]; dir?: string }> = {
  en: { name: "English", nativeName: "English", words: english },
  hi: { name: "Hindi", nativeName: "हिन्दी", words: hindi },
  id: { name: "Indonesian", nativeName: "Bahasa Indonesia", words: indonesian },
  tl: { name: "Tagalog", nativeName: "Tagalog", words: tagalog },
  es: { name: "Spanish", nativeName: "Español", words: spanish },
};

export const DEFAULT_LANGUAGE = "en";

// Generate a random set of words for a test session.
export function generateWords(lang: string, count: number = 60): string[] {
  const wordList = LANGUAGES[lang]?.words ?? LANGUAGES[DEFAULT_LANGUAGE].words;
  const shuffled = [...wordList].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
